export const STORAGE_CONFIG = {
  // Pinata JWT from environment variables
  PINATA_JWT: import.meta.env.VITE_PINATA_JWT || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIyYmNlOGNhZS0zZDQ3LTRhNjgtYmRjYS1hZWQ2ZjMzNjQ4ZTUiLCJlbWFpbCI6ImxhbmNlam9zZXBoLmVuYXJpb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiOGI4NGI2YzE1YWI4YjJmNGM4N2YiLCJzY29wZWRLZXlTZWNyZXQiOiJmNWIzMWRlYjJiZDYxMzBhYzVmMWEyOTRkYzc3M2ZkZDBjYWExZjVlMDU5NzE4ZmNiYWZmNWZlZTliMGJmMjRhIiwiZXhwIjoxODA1NTM4MzEwfQ.EYPovkm3Y8-uSfBfK2ytOKUUrycwDyAUyQ3bdYfqpWU',

  // Public IPFS gateway for retrieval (Pinata gateway is faster but public works too)
  IPFS_GATEWAY: 'https://gateway.pinata.cloud/ipfs/'
};
